version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: favmovies_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: favmovies_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: favmovies_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: favmovies
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: